setup-info-locations:
  - "http://mirrors.tuna.tsinghua.edu.cn/stackage/stack-setup.yaml"
urls:
  latest-snapshot: http://mirrors.tuna.tsinghua.edu.cn/stackage/snapshots.json
allow-newer: true
nix:
  pure: false
# Not for now, https://github.com/haskell/c2hs/issues/229
# ghc-options:
#   "$everything": -haddock
