[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.dprint]
command = "dprint"
options = ["fmt"]
includes = [
  "*.json",
  "*.toml",
  "*.md",
]

[formatter.luaformatter]
command = "lua-format"
options = ["-i"]
includes = ["*.lua"]
