[theme]
theme = "solarized-dark"
[icons]
icons = "awesome"

[[block]]
block = "focused_window"
autohide = true
[block.format]
full = "$title.rot-str(75)|"
short = "$title.rot-str(20)|"

[[block]]
block = "disk_space"
alert_unit = "GB"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "$mem_free.eng(3,B,M)"
format_swap = "$swap_free.eng(3,B,M)"

[[block]]
block = "cpu"

[[block]]
block = "load"

[[block]]
block = "sound"

[[block]]
block = "battery"
hide_missing = true
hide_full = true

[[block]]
block = "pomodoro"
notify_cmd = "notify-send $msg"
blocking_cmd = false

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
